### ISSUE TITLE
Titanium CLI not installing

### ISSUE THREAD

**Issue by justatad44** [tidev/titanium#552]
I'm trying to install titanium CLI and I keep getting the following error:

npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.

I can't install encoding 0.1.0 because it does not exist. I tried installing the latest node-fetch and the latest encoding, but still get the same error when trying to install titanium.

Just for reference, I've been using the Appcelerator CLI for some time, but it stopped working today because of the login requirement (no longer supported). I'd be interested to know if there's an alternative workaround...

**Comment by simarpreetsinghkalra** [comment]
> I'm trying to install titanium CLI and I keep getting the following error:
> 
> npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
> 
> I can't install encoding 0.1.0 because it does not exist. I tried installing the latest node-fetch and the latest encoding, but still get the same error when trying to install titanium.
> 
> Just for reference, I've been using the Appcelerator CLI for some time, but it stopped working today because of the login requirement (no longer supported). I'd be interested to know if there's an alternative workaround...

Please share more information like

- Command you ran
- screenshots of the error

I also got the issue with Appcelerator CLI but I have successfully installed Titanium CLI

**Comment by justatad44** [comment]
I was finally able to get it working...
