### ISSUE TITLE
How to build Appcelerator iOS app?

### ISSUE THREAD

**Issue by Sean-Brown-Digi** [tidev/titanium#553]
Since Appcelerator was end-of-lifed on March 1st, the Appcelerator CLI no longer works for me to run or build the app.
Using the Titanium CLI directly allows me to build and run my app, but it only works for Android. Whenever I try to build or run the app for iOS, I receive the following error:
`[ERROR] titanium_prep failed to run (10)`
`[ERROR] This application cannot be built with the Titanium open source SDK because it is an Appcelerator Platform registered application. Please use the Appcelerator Platform CLI tools or Appcelerator Studio to build this application.`

I don't understand why Android works and iOS doesn't, and I've been unable to find anything on the Axway blog that mentions this, so how are you supposed to build the app for iOS?

**Comment by cb1kenobi** [comment]
@Sean-Brown-Digi please follow this guide for how to migrate from the Appc CLI to the Titanium CLI: https://github.com/m1ga/from_zero_to_app/blob/master/appc_to_ti.md

**Comment by Sean-Brown-Digi** [comment]
Perfect, that worked
